var infoname = [
    "實用小工具 🔧",
    "學校及報告📏",
    "娛樂🎮",
    "程式設計💻",
    "知識充電站👀",
    "高中升學輔導專區💼",
    "Google and Microsoft",
    "AI💥"]

var info = [
    /*工具*/
    [["https://www.ilovepdf.com/zh-tw", "ilovepdf", "ilovepdf.png"],
    ["https://www.canva.com/", "canva", "canva.svg"],
    ["https://www.pexels.com/zh-tw/", "pexels", "pexels.png"],
    ["https://www.flaticon.com/", "flaticon", "flaticon.jpg"],
    ["https://reurl.cc", "reurl", "reurl.png"],
    ["https://fonts.google.com/", "google fonts", "googlefonts.png"],
    ["https://unsplash.com/", "unsplash", "unsplash.svg"],
    ["https://thepopp.com/templates/scheat/", "Power of PPT", "popp.svg"],
    ["https://www.notion.so/", "notion", "notion.svg"],
    ["https://www.fontspace.com/", "fontspace", "fontspace.jpg"],
    ["https://vectorwiki.com", "vectorwiki", "vectorwiki.png"],
    ["https://free.com.tw/", "free sources", "free.jpg"],
    ["https://pinterest.com", "pinterest", "pinterest.png"],
    ["https://undraw.co/illustrations", "undraw", "undraw.png"],
    ["https://www.youtube.com/@audiolibrary_", "audio library", "audiolibrary.jpg"],
    ["https://xmind.app/", "xmind", "xmind.svg"],
    ["https://www.overleaf.com/", "overleaf", "overleaf.svg"],
    ["https://www.aconvert.com/tw/icon/png-to-ico/", "PNG轉ICO", "ico.jpg"],
    ],
    /*學校*/
    [["https://www.shs.edu.tw/", "中學生網站", "中學生.png"],
    ["https://ndltd.ncl.edu.tw/", "博碩網", "博碩網.jpg"],
    ["https://epf-mlife.k12ea.gov.tw/", "學習歷程上傳", "學習歷程.png"],
    ["http://210.70.188.193/skyweb/index.htm", "揚子高中", "yths.png"],
    ["https://twsf.ntsec.gov.tw/", "科教館", "科教館.png"],
    ["https://www.ntsec.edu.tw/science/list.aspx", "網路科教館", "科教館.png"],
    ["https://twpat3.tipo.gov.tw/", "專利檢索", "IPO.png"],
    ["http://www.ieyiun.org/", "IEYI", "ieyi.png"],
    ["https://innoserve.tca.org.tw/", "InnoServe", "innoserve.gif"],
    ["https://www.mxeduc.org.tw/scienceaward/", "旺宏科學獎", "旺宏.jfif"],
    ["https://tepu.org.tw/", "小水力", "tepu.png"],
    ["https://www.ewant.org/", "ewant", "ewant.jpg"],
    ["http://ocw.aca.ntu.edu.tw/ntu-ocw/", "台大開放式課程", "台大.svg"],
    ["https://students.tw/", "高中生資訊網", "student.jpg"]],
    /*娛樂*/
    [
    ["https://open.spotify.com/", "spotify", "spotify.svg"],
    ["https://www.messenger.com/", "messenger", "messenger.svg"],
    ["https://www.instagram.com/", "instagram", "Instagram.svg"],
    ["https://www.facebook.com/", "Facebook", "facebook.svg"],
    ["https://twitter.com/", "twitter", "twitter.svg"],
    ["https://discord.com/app", "discord", "discord.svg"],
    ["https://www.dcard.tw/", "dcard", "dcard.png"],
    ["https://ani.gamer.com.tw/", "巴哈姆特動畫瘋", "anime.jpg"],
    ["https://www.twitch.tv/", "twitch", "twitch.svg"],
    ["https://www.motorsport.com/", "motorsport", "motorsport.jpg"],
    ["https://www.autosport.com/", "autosport", "autosport.png"],
    ["https://www.sportsv.net/racing", "運動視界", "運動視界.jpg"]],
    /*程式*/
    [["https://www.w3schools.com/", "w3schools", "w3logo/logo.png"],
    ["https://github.com", "github", "github.png"],
    ["https://stackoverflow.com/", "stack overflow", "stackoverflow.jpg"],
    ["https://linktr.ee/ncku_csie_camp", "ncku_csie", "ncku_csie.jpg"],
    ["https://www.oxxostudio.tw/", "oxxostudio", "oxxo.png"],
    ["https://www.hello-algo.com/", "hello算法", "hello.png"],
    ["https://diagram.com/", "diagram", "diagram.svg"],
    ["https://www.figma.com/", "figma", "figma.png"],
    ["https://www.codecademy.com/", "codecademy", "codecademy.svg"],
    ["https://www.edx.org/", "edx", "edx.png"],
    ["https://www.khanacademy.org/", "khanacademy", "khan.svg"],
    ["https://www.udacity.com/", "udacity", "udacity.svg"],
    ["https://dash.generalassemb.ly/", "dash", "dash.png"],
    ["https://www.learneroo.com/", "learneroo", "learneroo.jpg"],
    ["https://bento.io/", "banto.io", "bento.svg"],
    ["https://www.freecodecamp.org/", "freecodecamp", "freecodecamp.svg"],
    ["https://leetcode.com/", "leetcode", "leetcode.png"],
    ["https://www.youtube.com/@TheCodingTrain", "the coding train", "thecodingtrain.jpg"],
    ["https://ai2.appinventor.mit.edu/", "app inventor", "appinventor.png"]],
    /*學習*/
    [["https://tw.voicetube.com/", "voicetube", "voicetube.svg"],
    ["https://www.bbc.co.uk/learningenglish/", "BBCEng", "bbc.png"],
    ["https://www.youtube.com/user/crashcourse", "Crash Course", "crashcourse.png"],
    ["https://www.youtube.com/c/TED", "TED", "ted.svg"],
    ["https://quizlet.com/", "Quizlet", "quizlet.svg"],
    ["https://www.coolenglish.edu.tw/", "cool english", "coolenglish.png"],
    ["https://www.etymonline.com/", "etymonline", "etymonline.jpg"],
    ["https://dictionary.cambridge.org/", "劍橋辭典", "cambridge.png"],
    ["https://www.merriam-webster.com/", "韋氏字典", "webster.jpg"],
    ["https://www.theguardian.com/science", "Guardian", "guardian.svg"],
    ["https://radio.garden/", "radio garden", "radio.png"],
    ["https://www.junyiacademy.org/", "均一", "均一.svg"],
    ["https://philomedium.com/", "哲學新媒體", "philomedium.png"],
    ["https://lawplayer.com/", "lawplayer", "lawplayer.jpg"],
    ["https://www.goodreads.com/quotes", "Quotes", "goodreads.jpg"],
    ["https://dict.revised.moe.edu.tw/", "教育部辭典", "dict.png"],
    ["https://www.cia.gov/the-world-factbook/", "the world's factbook", "factbook.png"],
    ["https://www.twreporter.org/", "報導者", "thereporter.svg"],
    ["https://www.peopo.org/", "PEOPO", "peopo.jpg"],
    ["https://den.ncdr.nat.gov.tw/", "全球災害事件簿", "disaster.svg"],
    ["https://medium.com", "medium", "medium.svg"],
    ["https://www.snexplores.org/", "SNExplores", "sn.svg"],
    ["https://taxonomicdune.com/", "分類沙丘", "sn.svg"],
    ["https://www.science.org/", "AAAS", "aaas.svg"],
    ["https://highscope.ch.ntu.edu.tw/", "科學online", "online.jpg"],
    ["https://jacoboneal.com/", "Jacob O'Neal", "JO.png"],
    ["https://www.geogebra.org/", "geogebra", "geogebra.png"],
    ["https://pansci.asia/", "泛科學", "pansci.jpg"]
    ],
    /*升學*/
    [["https://collego.edu.tw/", "collego", "collego.svg"],
    ["https://ioh.tw/", "IOH", "ioh.jpg"],
    ["https://www.unews.com.tw/", "大學問", "大學問.jpg"],
    ["https://www.cac.edu.tw/", "大學聯招", "college.jpg"],
    ["https://career.cloud.ncnu.edu.tw/", "生涯輔導網", "career.png"],
    ["https://srecruit.moe.edu.tw/", "特殊選才", "特殊選才.jpg"],
    ["https://www.ceec.edu.tw/", "大考中心", "大考中心.jpg"],
    ["https://nsdua.moe.edu.tw/", "多元入學", "多元入學.jpg"],
    ["https://university.1111.com.tw/", "1111大學網", "1111大學網.jpg"],
    ["https://www.104.com.tw/jb/career/", "104求職網", "104.svg"]],
    /*google and microsoft*/
    [["https://www.google.com/", "search", "googlesearch.png"],
    ["https://www.youtube.com/", "YouTube", "YouTube.svg"],
    ["https://music.youtube.com/", "YouTube Music", "youtubemusic.png"],
    ["https://mail.google.com/", "gmail", "gmail.png"],
    ["https://pagespeed.web.dev/", "pagespeed insights", "pagespeed.png"],
    ["https://translate.google.com/", "translate", "translate.png"],
    ["https://drive.google.com/", "drive", "drive.png"],
    ["https://keep.google.com/", "keep", "keep.png"],
    ["https://classroom.google.com/", "classroom", "classroom.png"],
    ["https://chrome.google.com/webstore/", "web store", "webstore.svg"],
    ["https://photos.google.com/", "photo", "photo.svg"],
    ["https://www.google.com/maps/", "map", "map.png"],
    ["https://meet.google.com/", "meet", "meet.png"],
    ["https://docs.google.com/drawings/", "drawings", "drawing.png"],
    ["https://www.kaggle.com/", "kaggle", "kaggle.svg"],
    ["https://podcasts.google.com/", "podcast", "podcast.png"],
    ["https://to-do.live.com/tasks/", "to-do", "todo.svg"],
    ["https://www.bing.com/", "bing", "bing.jpg"],
    ["https://www.office.com/", "office", "office.png"]],
    /*AI*/
    [["https://chat.openai.com", "chatGPT", "chatgpt.jpg"],
    ["https://claude.ai/", "claude", "claude.svg"],
    ["https://bard.google.com/", "bard", "bard.jpg"],
    ["https://app.leonardo.ai/", "Leonardo", "leonardo.png"],
    ["https://www.naturalreaders.com/", "Natural Readers", "nr.svg"],
    ["https://www.fotor.com/", "fotor", "fotor.png"],
    ["https://designer.microsoft.com", "msdesigner", "msdesigner.jpg"],
    ["https://tome.app/", "tome", "tome.png"],
    ["https://gamma.app/", "gamma", "gamma.jpg"],
    ["https://scribblediffusion.com/", "scribblediffusion", "scribblediffusion.jpg"]]
]